markdown: kramdown
theme: jekyll-theme-minimal
title: 'Cooking Journal'
author:
  name:  '\0/ Buro and Maggie <3'
timezone: UTC−07:00
baseurl: /cooking_journal
logo: /assets/images/favicon.png
plugins:
- jekyll-feed
- jekyll-mentions
- jekyll-paginate
paginate: 6
paginate_path: /page/:num/
